### ISSUE TITLE
Allocating string slices

### ISSUE THREAD

**Issue by vorner** [SimonSapin/rust-typed-arena#37]
Hello

If I'm not mistaken, if I have a lot of smallish strings, they have non-trivial overhead in the allocator. So using an arena should help in this use case.

However, string slices are something a bit weird and it doesn't seem to be an easy way to allocate them using the `Arena` type. What I figured can be done is this:

```rust
fn alloc_str<'a>(arena: &'a Arena<u8>, s: &str) -> &'a str {
    let buffer = arena.alloc_extend(s.bytes());
    str::from_utf8(buffer).unwrap()
}
```

This works, but has two downsides:
* It pushes this code to the user.
* The `from_utf8` does needless second validation. One could use `unsafe` and `from_utf8_unchecked`, but in general applications like to avoid placing `unsafe` close to any business logic.

Would it be OK if I send a pull request to support string slices into this crate? I can think of adding the above as method of `Arena<u8>`, or wrapping it into a separate `StrArena` type. Which one would be preferred?

**Comment by fitzgen** [comment]
Thanks for filing an issue.

We could add this `alloc_str` method to an `Arena<u8>`, but in this particular case, I think [`bumpalo`](https://github.com/fitzgen/bumpalo) is better suited to this problem:

* it already has `alloc_slice_{copy, clone}` methods: https://docs.rs/bumpalo/2.6.0/bumpalo/struct.Bump.html#method.alloc_slice_copy

* on master, it has `with` variants of those, that reliably avoid the construct-on-the-stack-and-move-into-the-heap problem that Rust is often plagued with

* I'm open to adding`str`-specific methods to `Bump`, to let users avoid transmuting `&[u8]` slices manually

* It doesn't require choosing between defining and maintaining a whole new wrapper type vs putting methods on "unexpected" types (string stuff on `Arena<u8>`)

**Comment by vorner** [comment]
I've already put a pull request there in the meantime (https://github.com/fitzgen/bumpalo/pull/50), but as I was checking both crates if one has the feature I looked for, I thought both could benefit from it.

I'm fine closing this if the „official“ stance is to go with bumpalo.

**Comment by fitzgen** [comment]
Oh sweet!

FWIW, I'm still fine with adding `Arena<u8>::alloc_str` here, I just think it is pretty funky, and if all else is equal, then folks will probably be better off with `bumpalo`.

So basically, it is up to you: if you want to add it here as well, we can do that, otherwise I'll close this issue.

**Comment by vorner** [comment]
OK, I'll send a PR, probably this weekend.
