### ISSUE TITLE
Should alloc_unitialized return MaybeUninit?

### ISSUE THREAD

**Issue by vorner** [SimonSapin/rust-typed-arena#38]
When reading through the docs, I've stumbled on this function:

https://docs.rs/typed-arena/1.7.0/typed_arena/struct.Arena.html#method.alloc_uninitialized

This returns a pointer to array of `T`s. Once one starts accessing the array, I think similar issues about impossible to handle correctly as the original `std::mem::unitialized()` would raise, eg. no legal way to even initialize it if `T=bool`.

Should such function be deprecated and replaced by something returning `MaybeUninit` as well?

**Comment by fitzgen** [comment]
Yeah, this method predates `MaybeUninit`, but it definitely should be updated to use `MaybeUninit` now.

**Comment by vorner** [comment]
I can send the PR, then. I just want to sync about it first:

* Replace it, or add a new one and deprecate the old one?
* Would the right type be `fn alloc_unitialized(&self, len: usize) -> *mut [MaybeUninit<T>]`? I guess so, because `-> *mut MaybeUninit<[T]>` probably wouldn't work.
* Should the same be done with `uninitialized_array`?

And one more thing. If I call `alloc_uninitialized`, forget to initialize and destroy the arena, I assume it'll try to run destructors on all these uninitialized elements. So even with using the `MaybeUninit`, panicking at the wrong time is going to explode. Should we come up with some safer protocol where the caller first asks for the space, then initializes it and then confirms the allocation? The first would act a bit like `uninitialized_array`, but one could require it to be some specific length (eg. make the arena allocate another chunk if need be).

**Comment by fitzgen** [comment]
> Replace it, or add a new one and deprecate the old one?

I think we can replace it and do a breaking release.

> Would the right type be `fn alloc_unitialized(&self, len: usize) -> *mut [MaybeUninit<T>]`? I guess so, because `-> *mut MaybeUninit<[T]>` probably wouldn't work.

Yeah, it is unfortunate that there doesn't exist some sort of transpose-esque method for going between the two.

> Should the same be done with `uninitialized_array`?

Yeah.

> So even with using the `MaybeUninit`, panicking at the wrong time is going to explode

Yeah, this hazard also exists with the uninitialized methods right now.

> Should we come up with some safer protocol where the caller first asks for the space, then initializes it and then confirms the allocation?

This is sort of what the `with` methods on `bumpalo::Bump` do.
