### ISSUE TITLE
Lower performance than recursive `Box`ing with 1000s of allocations

### ISSUE THREAD

**Issue by jadennnn** [SimonSapin/rust-typed-arena#45]
Hi,

(First off, thanks for the crate!)

`typed-arena` seemed the perfect crate for my use-case: building a dynamic tree structure at runtime that would be read throughout the program but not modified once built. I build it recursively, with each parent node constructing children nodes (if they indeed have children) based on relatively expensive heuristics. Some possibly-relevant info about this tree:
- Each node holds two 3D vectors and a list of references to other prior-calculated data, as well as their children (up to 8 children). 
- Nodes only know about their direct children (if they have any).
- Average worst-case trees have several thousand nodes. These cases are common enough that they are the ones I'm developing around.
- CPU/wall-time performance is a priority over memory usage, within reason
- Single-threaded
- 2ms-120ms wall time for the entire system to run once, depending on which data the specific benchmark gives it. According to `perf` & flamegraphs, building this tree structure takes ~1/5 the time.

I originally just used the `Box`ing strategy, where the `children` field type was a `Option<Box<[Option<Node>; 8]>>`. However I wanted more performance and decided `typed-arena` should perform better than this recursive boxing strategy. This `children` field type became `Option<[Option<&'a Node<'a>>; 8]>`. Since I can conservatively estimate the total number of nodes in the tree, I use `Arena::with_capacity()`.

After I switched to `typed-arena`, though, it runs consistently *worse*. Using the Criterion benchmark library, it's ~5% slower on average across 30 different benchmarks. I also can notice the difference by eyeballing `perf` flamegraphs.

Is my use-case not appropriate or is `typed-arena` slow at 1000s of nodes?

**Comment by fitzgen** [comment]
This crate was originally a port to stable of a similar arena from inside `rustc`, but in the process of pulling it out a lot of it was rewritten to be more obviously safe, and do less unsafe optimization bits.

Which is to say that I'm not terribly surprised by what you describe.

I semi-passively maintain this crate just because it has a fair amount of usage out in the ecosystem, but as far as digging pretty deep into perf, I would just recommend [`bumpalo`](https://github.com/fitzgen/bumpalo) instead.

**Comment by jadennnn** [comment]
Ah yes that makes sense.
Using `bumpalo` with the `collections` feature looks like what I need, thanks!
