### ISSUE TITLE
Consider removing RefCell

### ISSUE THREAD

**Issue by ndmitchell** [SimonSapin/rust-typed-arena#48]
The typed-arena package is great! Much appreciated - it's been very useful for me.

The one thing that surprised me, and that has caused some slight annoyances in the API, is the fact that you have a RefCell inside the arena. That makes the type no longer Send or Sync. I have the programming model where I create an arena, mutate it a lot, then stop mutating it and start sharing it between threads. It's very natural to do that with:

```
let mut arena = Arena::new();
while ... {
    arena.alloc(...)
}
let arena = Arc::new(arena);
for lots of threads {
   ... send them an arena, some arena allocated values, and do some work
}
```

The RefCell first makes the `mut` unnecessary (which makes Rust tracking and understanding slightly harder), and adds some (probably negligible) overhead to the Arena operations. Next, the RefCell makes it hard to share things via the thread.

My initial thought was to remove the RefCell, and then let people who wanted the API in a RefCell wrap it themselves. Or is the RefCell required for other reasons?

**Comment by fitzgen** [comment]
The design has always been that the arena should be share-able and you should be able to allocate from it without threading through mutable references everywhere, similar to the global allocator, for example.

This crate is depended upon by a bunch of other crates, and is in maintenance mode. I don't think it is worth it to pursue large API changes. However, I agree that your use case isn't well-served by this crate, and that you want a completely reasonable thing. I'd encourage you to fork this crate, or maybe `bumpalo`, and see tailor it to your needs.

**Comment by ndmitchell** [comment]
Thanks for the comments - that makes sense - I appreciate the explanation. I think I can wrap the crate to give what I need, so I'm happy. The features of this crate like homogenous storage and calling Drop are helpful for my usage, so I think this still suits me better than `bumpalo`.
