### ISSUE TITLE
[&,&mut,]Arena does not implement IntoIterator

### ISSUE THREAD

**Issue by ubsan** [SimonSapin/rust-typed-arena#6]
It would be a very nice thing to have.

**Comment by ubsan** [comment]
... I now realize why it doesn't. Closing, sorry for the wasted issue!

**Comment by neverfox** [comment]
@ubsan I'm not having the same epiphany. Can you explain?

**Comment by SimonSapin** [comment]
`Arena::alloc` returns `&mut T`, which can be the only reference to that value as long as it exists.

The method could be changed to return `&T`, in which case a `Iterator<Item=&'arena T>` could be safely added (but not `Iterator<Item=&'arena mut T>`). But that would remove the ability to mutate without `Cell` (or similar) after inserting in the arena. So it’s a trade-off.

**Comment by jrmuizel** [comment]
I made a version of typed-arena that that returns `&T` instead: https://crates.io/crates/typed-arena-nomut
