### ISSUE TITLE
Potential soundness issue (stacked borrows): Is alloc_fast_path persisting borrows too long?

### ISSUE THREAD

**Issue by Manishearth** [SimonSapin/rust-typed-arena#62]
https://github.com/thomcc/rust-typed-arena/blob/f1f26c3994dc881c35591cb629d8466df29e778a/src/lib.rs#L193-L205

It's unclear to me if this is sound under stacked/tree borrows.

Essentially, the lifetime of the `*chunks` mutable place is less than that of the function, and when we call `chunks.current.as_mut_ptr()` we materialize an `&mut Vec<T>` for the receiver, but then we return a reference within there that lives longer.

My understanding of how these things interact with cells is that from the purposes of these rules cell types behind references can do things that would not be allowed from the general rules of working with a reference, _but_ that doesn't apply to references obtained from _within_ a cell, which is what's happening here.

As far as I can see there's no actual _safe_ way to do this currently (but it is absolutely something that _ought_ to be safe): we need a way to get the ptr behind a vector without materializing a reference to it, and there is currently no `self: *mut Self` Vec API for this. (We essentially need the equivalent of `addr_of!()` but for vector fields). So personally this does not worry me too much since "this is unsafe according to currently-in-flux rules but there is no safe way to  handle this use case" to me means that we should raise the use case with the folks making the rules and wait for the right APIs.

I also understand that UCG has been trying to figure out the balance on recursive validity and stuff, and Miri does not _currently_ complain on this.

So this might be fine in the end, but I do think we should talk about it and raise this use case with UCG so we can get a ruling and folks can ensure the stdlib gets the appropriate APIs as needed.

**Comment by Manishearth** [comment]
Well I guess _one_ safe way to do this is to only store raw pointers, but that does kinda suck

**Comment by Manishearth** [comment]
Also opened a [zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/136281-t-opsem/topic/is.20this.20typed_arena.20code.20sound.20under.20stacked.2Ftree.20borrows.3F) to get feedback from people who understand these rules better than I do.

**Comment by thomcc** [comment]
I think `vec.as_mut_ptr()` deliberately doesn't materialize a slice for this reason, but perhaps I'm misunderstanding the issue.

**Comment by Manishearth** [comment]
@thomcc it does because `as_mut_ptr()` has an `&mut Self` receiver.

(this kind of thing is exactly why `addr_of!()` exists)

**Comment by Manishearth** [comment]
However, AIUI UCG does not want types like Vec to be special here, so _maybe_ this is still fine and the stacked borrow does not poke through the vec.

**Comment by thomcc** [comment]
the `&mut Self` only applies to the Vec, not to the pointer it holds (which is inside the RawVec).

**Comment by Manishearth** [comment]
Yeah, I'm convinced. We're fine as long as Vec isn't special and so far I have mostly heard noises that Vec is _not_ special.

**Comment by Manishearth** [comment]
Also relevant, from Ralf:

> Stacked Borrows and Tree Borrows are strictly 1-layer, they don't go recurisvely looking for nested references

**Comment by RalfJung** [comment]
> Yeah, I'm convinced. We're fine as long as Vec isn't special and so far I have mostly heard noises that Vec is not special.

Cc https://github.com/rust-lang/unsafe-code-guidelines/issues/326

**Comment by Manishearth** [comment]
Ah, thanks, I was going to go digging for that in a bit :smile:

**Comment by Manishearth** [comment]
Opened https://github.com/rust-lang/rust/pull/113859 upstream to document the common-sense-but-not-guaranteed invariant that this code relies on.
